### ISSUE TITLE
Add developer guide

### ISSUE THREAD

**Issue by morazow** [exasol/spark-connector-common-java#4]
### Situation

Add developer guide, with short description related to the develops.

- Add notice on using `provided` scope for the Spark dependencies

### Acceptance Criteria

- Developer guide is added

**Comment by ckunki** [comment]
Hi @morazow I set the PR to "approved" and left a comment for an optional change. 
If you want to apply this change then just ping me for final approval.

**Comment by morazow** [comment]
Great, I added them, please have another look.
